### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by slifszyc** [stephenmathieson/duo-stylus#5]
I have:
```
|- index.styl // entry-point
|- lib
    |-- boot.styl
    |-- images
        |-- bg.jpg
```

index.styl:
```
body
  background red

@import 'lib/boot/boot.styl'
```

boot.styl:
```
body
  background url('./images/bg.jpg')

body h1
  font-size 16px
```

When I run with the CLI: `duo --use duo-stylus index.styl --no-cache` I get a prompt for my github access token (password). The same happens with the Duo API:
```
var Duo = require('duo');
var stylus = require('duo-stylus');
var fs = require('fs');
var path = require('path');
var join = path.join;
var mkdir = require('mkdirp').sync;

var build = join(__dirname, 'build');
var out = join(build, 'build.css')

mkdir(build);

var duo = new Duo(__dirname);

duo.entry('index.styl').use(stylus()).cache(false);

duo.run(function(err, results) {
  if (err) throw err;
  fs.writeFileSync(out, results.code);
  var len = Buffer.byteLength(results.code);
  console.log('all done, wrote %dkb', len / 1024 | 0);
});
```

The only workaround I found is having this on `boot.styl`:
```
body
  background url('lib/boot/images/bg.jpg')

body h1
  font-size 16px
```

Can I write it somehow in the first way?

**Comment by stephenmathieson** [comment]
Duo requires you to authenticate with GitHub.  See [Duo's readme](https://github.com/duojs/duo#authenticate-with-github) for details.

When your `boot.styl` file has no dependencies (no `import` statements), Duo knows it won't have to hit any of GitHub's APIs and doesn't ask you for your password.
